### PR TITLE
Improvement

### PR DESCRIPTION
**Pull request by TechnicalStudioDeveloper**
New Sketchware official doc link placed.
Misspelled type p to type c.
Some grammer improvement.

### CODE REVIEW

**Comment by TechnicalStudioDeveloper** [comment]
@NiceSapien

**Comment by NiceSapien** [comment]
> @NiceSapien

@TechnicalStudioDeveloper 
Hello!
First, thanks for the contribution.
Second, please don't always ping me in every issue or PR. When i get time, I will manually check prs.

**Comment by TechnicalStudioDeveloper** [comment]
> > @NiceSapien
> 
> @TechnicalStudioDeveloper Hello! First, thanks for the contribution. Second, please don't always ping me in every issue or PR. When i get time, I will manually check prs.

You are not watching this repo so thought you do not receive notifications.

**Comment by NiceSapien** [comment]
> > > @NiceSapien
> > 
> > 
> > @TechnicalStudioDeveloper Hello! First, thanks for the contribution. Second, please don't always ping me in every issue or PR. When i get time, I will manually check prs.
> 
> You are not watching this repo so thought you do not receive notifications.

i dont even check notifications tbh

**Review by NiceSapien — APPROVED** [review]
Nice.

**Pull request merged**
