### PR TITLE
Connecting to firebase update

### PR DESCRIPTION
**Pull request by TechnicalStudioDevelopers**
Connect to firebase changes
1.Firebase is not free but it is free under limits.
2.Firebase is secure by using firebase rules.

### CODE REVIEW

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien please provide commands to run this website in emulator or something I always get error while I run this website

**Comment by NiceSapien** [comment]
Which emulator are you using, what is the operating system, and are you trying to build and test this website or trying to load https://sketchware-pro.ga and getting error?

**Comment by TechnicalStudioDevelopers** [comment]
> Which emulator are you using, what is the operating system, and are you trying to build and test this website or trying to load https://sketchware-pro.ga and getting error?

VS code terminal(Windows 10)

**Comment by TechnicalStudioDevelopers** [comment]
docusaurus: not found
error Command failed with exit code 127

**Comment by NiceSapien** [comment]
> docusaurus: not found
> error Command failed with exit code 127

Please read the README.md's contributing guide always before contributing. 
1. Always push in the Dev branch.
2. It is clearly stated,
```cmd
npm install
npm start
```

I will merge this time, please don't consider me rude or smth, i just wanted to help. If you still face problems, please comment down.

**Comment by NiceSapien** [comment]
Merging and closing this. Please move to the issue.

**Pull request merged**
