### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by TechnicalStudioDevelopers**
I have added More block and Importing block documentation please review this pull request.

### CODE REVIEW

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien Please tell me how to add On this page in .md files.

**Comment by NiceSapien** [comment]
Ok i will push need some time to review

**Comment by TechnicalStudioDevelopers** [comment]
> Ok i will push need some time to review

I have not changed any file that doesn't relate to docs

**Comment by NiceSapien** [comment]
I think it'll change automatically in production

**Comment by TechnicalStudioDevelopers** [comment]
> I think it'll change automatically in production Did you use git command line for commiting?

I used `git commit -m "msg"`

**Comment by TechnicalStudioDevelopers** [comment]
Is there any problem??

**Comment by NiceSapien** [comment]
> Is there any problem??

Did yiu login with ssh

**Comment by TechnicalStudioDevelopers** [comment]
> > Is there any problem??
> 
> Did yiu login with ssh

I used github token

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien I meant that I there any problem in pull req.?
If not why are you not merging this pull req.

**Comment by NiceSapien** [comment]
I'll merge it soon

**Comment by NiceSapien** [comment]
image
please fix all the errors first. You might need to use Grammarly

**Comment by TechnicalStudioDevelopers** [comment]
> image please fix all the errors first. You might need to use Grammarly

@NiceSapien I don't have premium account.
So I will not able to fix premium suggestions

**Comment by NiceSapien** [comment]
Please fix normal ones then

**Comment by TechnicalStudioDevelopers** [comment]
> Please fix normal ones then

Ok

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien there are some code like `tag : ...` which should not be changed so In my opinion you will see error if they fixed by grammarly.
I will not change them for the error Chance's

**Comment by TechnicalStudioDevelopers** [comment]
@NiceSapien fixed grammer and added a doc.

**Comment by NiceSapien** [comment]
Alright. Please remove the page which has the modders as this is no longer official website.

**Comment by TechnicalStudioDevelopers** [comment]
> Alright. Please remove the page which has the modders as this is no longer official website.

Which page??Any link?

**Comment by TechnicalStudioDevelopers** [comment]
Removed : Contributors.mf

**Review by NiceSapien — APPROVED** [review]
Merge.

**Pull request merged**
