### PR TITLE
New Docs, Improvement, New Blog

### PR DESCRIPTION
**Pull request by DevKumar00001**

### CODE REVIEW

**Comment by NiceSapien** [comment]
Hey! I checked your PR today, and will merge it. But please fix the following issues first:
1. Sketchware Pro - needs a Capital `P` where ever you type the name. `Pro` is a part of the name after all, so it needs to be in capital. If possible, please fix it. If not, it's OK, I'll merge without that.
2. Please change the title of the blog(`Sketchware pro is a revolutionary app`) to something else, such as `Sketchware Pro can change the future of Android App development` or such.
3. I would like to thank you from the heart for working on this website! You were the only one who wanted to help me build it. Now I'm thinking of creating a full Sketchware Pro course. I hope you can help me.

Thanks!

**Comment by TechnicalStudioDeveloper** [comment]
However I also want to create a guide book earlier but I have not one to help in that So leaved that.
This is the [link](https://www.dropbox.com/scl/fi/xek8j34r3sh37y6usvb8j/pdf_20230619_074003_0000.pdf?rlkey=bsem52cjk2n3m95ys8vtme68p&dl=0) of pdf.

**Comment by TechnicalStudioDeveloper** [comment]
@NiceSapien This is this [pdf](https://www.dropbox.com/scl/fi/xek8j34r3sh37y6usvb8j/pdf_20230619_074003_0000.pdf?rlkey=bsem52cjk2n3m95ys8vtme68p&dl=0) out or not?

**Comment by NiceSapien** [comment]
I loved the PDF! But I believe that people do not read/like to read a pdf. I think we should build a blog instead. Though the pdf is really nice too.

**Comment by TechnicalStudioDeveloper** [comment]
> I loved the PDF! But I believe that people do not read/like to read a pdf. I think we should build a blog instead. Though the pdf is really nice too.

I wanted to create full docs for that but you website doesn't have full access to css html and javascript for better website.As Docusoras has limited features

**Review by NiceSapien — CHANGES_REQUESTED** [review]
Please change "Java developer" to your role related to website, Contributor for now. Thanks!

**Comment by DevKumar00001** [comment]
> Please change "Java developer" to your role related to website, Contributor for now. Thanks!

It is already contributor.

**Review by NiceSapien — APPROVED** [review]
Merging.

**Comment by NiceSapien** [comment]
Merged!

**Pull request merged**
